---
- hosts: test
  remote_user: root
  tasks:
  - name: include variables
    include_vars: vars.yml
  - name: ensure ts3 directory exists
    file: path={{ host_vol }} state=directory owner=503 group=503
  - name: remove container
    docker_container:
      name: "{{ container_name }}"
      state: absent
  - name: update container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      state: started
      pull: true
      volumes:
        - "{{ host_vol }}:{{ container_vol }}"
      ports:
        - "9987:9987/udp"
        - "30033:30033"
        - "10011:10011"
        - "41144:41144"
      env:
          "{{ license_var }}": accept
